title: Milo
description: A Fully Autonomous Indoor/Outdoor Robotic Guide Dog
theme: jekyll-theme-cayman
show_downloads: false
# Replace with your arXiv abs URL once available
arxiv_url: https://arxiv.org/abs/XXXX.XXXXX
github_url: https://github.com/fgolemo/milo
youtube_id: Fz7sLqQHArY
